# Environment Requirements
minecraft_version=26.3
mc_version_number=260300
java_version=25

# Pack Formats
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=121
resource_pack_format=97

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_version=0.161.0+26.3

# Polymer Dependency
# check this on https://maven.nucleoid.xyz/eu/pb4/polymer-core/
polymer_version=0.18.2+26.3
